def default_configuration():
    return {
    "initialStartUp": True,
    "configurationPassword": "",
    "globalConfiguration": {
        "language": "en",
        "colorMode": "light",
        "alertColor": "000000",
        "highlightColor": "000000",
        "protectionLevel": 1,
    },
    "swebConfiguration": {
        "swebAllowedUrlListV2": [
            {"url1": "https://irozhlas.cz/", "icon1": "icons/sweb_www_1.png"},
            {
                "url2": "https://edition.cnn.com/",
                "icon2": "icons/sweb_www_2.png",
            },
            {"url3": "https://www.vut.cz/", "icon3": "icons/sweb_www_3.png"},
            {"url4": "https://google.com/", "icon4": "icons/sweb_www_4.jpg"},
            {
                "url5": "https://www.aktualne.cz/",
                "icon5": "icons/sweb_www_5.png",
            },
            {"url6": "https://www.denik.cz/", "icon6": "icons/sweb_www_6.png"},
        ],
        "urlsForWebsites": [
            "https://irozhlas.cz/",
            "https://edition.cnn.com/",
            "https://www.vut.cz/",
            "https://www.info-zdravi.cz/",
            "https://www.aktualne.cz/",
            "https://www.denik.cz/",
        ],
        "picturePaths": [
            "icons/exit.png",
            "icons/sweb_www_1.png",
            "icons/sweb_www_2.png",
            "icons/sweb_www_3.png",
            "icons/sweb_www_4.png",
            "icons/sweb_www_5.png",
            "icons/sweb_www_6.png",
        ],
        "allowedURL": "phish/sweb_allowed_url.txt",
        "phishingDatabase": "phish/sweb_phish.txt",
        "phishingGithubDatabase": "https://github.com/mitchellkrogza/Phishing.Database/raw/master/ALL-phishing-domains.tar.gz/",
        "sendPhishingWarning": True,
        "phishingFormular": True,
        "seniorWebsitePosting": True,
        "whiteListedWebsitesOnly": False,
        "allowWebSearch": True,
        "defaultLanguage": "cz",
        "text": [
            "MENU 1",
            "MENU 2",
            "Search",
            "MENU 1",
            "MENU 2",
            "Vyhledávání",
            "MENU 1",
            "MENU 2",
            "Suche",
        ],
    },
    "smailConfiguration": {
        "seniorEmail": "xfiala59@gmail.com",
        "seniorPassword": "pafotbpfrrlwvund",
        "smtpServer": "smtp.gmail.com",
        "smtpPort": 587,
        "imapServer": "imap.gmail.com",
        "imapPort": 993,
        "careGiverEmail": "",
        "emailContactsV2": [
            {
                "email1": "sos.smail.person.1@gmail.com",
                "icon1": "icons/smail_person_1.png",
            },
            {
                "email2": "sos.smail.person.2@gmail.com",
                "icon2": "icons/smail_person_2.png",
            },
            {
                "email3": "sos.smail.person.3@gmail.com",
                "icon3": "icons/smail_person_3.png",
            },
            {
                "email4": "sos.smail.person.4@gmail.com",
                "icon4": "icons/smail_person_4.png",
            },
            {
                "email5": "sos.smail.person.5@gmail.com",
                "icon5": "icons/smail_person_5.png",
            },
            {
                "email6": "sos.smail.person.6@gmail.com",
                "icon6": "icons/smail_person_6.png",
            },
        ],
        "emailContacts": [
            "sos.smail.person.1@gmail.com",
            "sos.smail.person.2@gmail.com",
            "sos.smail.person.3@gmail.com",
            "sos.smail.person.4@gmail.com",
            "sos.smail.person.5@gmail.com",
            "sos.smail.person.6@gmail.com",
        ],
        "emailPicturesPath": [
            "icons/exit.png",
            "icons/smail_person_1.png",
            "icons/smail_person_2.png",
            "icons/smail_person_3.png",
            "icons/smail_person_4.png",
            "icons/smail_person_5.png",
            "icons/smail_person_6.png",
        ],
        "sendPhishingWarning": True,
        "showUrlInEmail": True,
        "receiveWhitelistedEmailsOnly": False,
        "sendWhitelistedEmailsOnly": False,
        "languageSet": {
            "smailEnSendToButton": "Send To",
            "smailEnInboxLabel": "Inbox:",
            "smailEnLoadingInbox": "Loading...",
            "smailEnRecipientLabel": "To: ",
            "smailEnSubjectLabel": "Subject: ",
            "smailEnMessageLabel": "Message: ",
            "smailEnFrom": "Information: ",
            "smailEnDate": "Date: ",
            "smailEnEmailSent": "Email has been sent.",
            "smailEnEmailFail": "Email has not been sent.",
            "smailEnUndeliveredEmail": "The email was not delivered to the address {recipient_email}.",
            "smailEnSensitiveContentWarning": "Warning: \nThe email contains sensitive information. \nPress the button a second time to send the email.",
            "smailEnUnconfirmedEmailWarning": "Warning: \nUnconfirmed email in progress. \nPress the button again to cancel.",
            "smailCzSendToButton": "Komu",
            "smailCzInboxLabel": "Doručená pošta: ",
            "smailCzLoadingInbox": "Načítám...",
            "smailCzRecipientLabel": "Příjemce: ",
            "smailCzSubjectLabel": "Předmět: ",
            "smailCzMessageLabel": "Zpráva: ",
            "smailCzFrom": "Informace: ",
            "smailCzDate": "Datum: ",
            "smailCzEmailSent": "E-mail byl úspěšně odeslán.",
            "smailCzEmailFail": "E-mail nebyl odeslán.",
            "smailCzUndeliveredEmail": "Email nebyl doručen na adresu {recipient_email}.",
            "smailCzSensitiveContentWarning": "Varování: \nEmail obsahuje citlivé údaje. \nStisknutím tlačítka podruhé email odešlete.",
            "smailCzUnconfirmedEmailWarning": "Varování: \nRozpracovaný email nebyl potvrzen. \nDalším stisknutím dojde k jeho zrušení.",
            "smailDeSendToButton": "Senden An",
            "smailDeInboxLabel": "Posteingang: ",
            "smailDeLoadingInbox": "Laden...",
            "smailDeRecipientLabel": "An: ",
            "smailDeSubjectLabel": "Betreff: ",
            "smailDeMessageLabel": "Nachricht: ",
            "smailDeFrom": "Information: ",
            "smailDeDate": "Datum: ",
            "smailDeEmailSent": "Die E-Mail wurde erfolgreich gesendet.",
            "smailDeEmailFail": "Die E-Mail wurde nicht gesendet.",
            "smailDeUndeliveredEmail": "Die E-Mail wurde nicht an die Adresse {recipient_email} zugestellt.",
            "smailDeSensitiveContentWarning": "Warnung: \nDie E-Mail enthält sensible Daten. \nDurch erneutes Drücken der Taste wird die E-Mail gesendet.",
            "smailDeUnconfirmedEmailWarning": "Warnung: \nUnbestätigte E-Mail in Bearbeitung. \nDrücken Sie die Taste erneut, um sie abzubrechen.",
        },
    },
}