on:
  push:
  workflow_dispatch:
    inputs:
      prerelease:
        default: true
        type: boolean
        required: true

name: Build ISO

jobs:
  build:
    permissions: 
      contents: write
    runs-on: ubuntu-24.04
    container: 
      image: archlinux
      options: --privileged
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install archiso
        run: pacman -Sy --noconfirm archiso
      - name: Build archiso
        run: |
          mkarchiso -v siso/src/archlive/
          mv out/archlinux** "out/senioros-`date +%Y-%m-%dT%H_%M`.iso"
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: senioros-iso
          path: out/

      - name: Release SeniorOS
        continue-on-error: true
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ hashFiles('out/*.iso') }}"
          prerelease: ${{ github.event.inputs.prerelease }}
          title: "SeniorOS ${{ github.event.repository.updated_at}}"
          files: |
            out/*.iso
